site_name: CS3244 PG26 Documentation
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - glightbox

# Navigation
nav:
  - Home: index.md
  - Navigating the repository: navigate-repo.md
  - Dataset: dataset.md
  - Motivation: motivation.md
  - Exploratory data analysis: eda.md
  - Data preprocessing: feature-engineering.md
  - Model design and creation: models.md
  - Lookahead bias: lookahead-bias.md
  - Model evaluation: evaluations.md
  - Credits: credits.md
  - "Appendix: Hyperparameters": hyperparameters.md
  - "Appendix: Biased results": results-biased.md
  - "Appendix: Unbiased results": results-unbiased.md

# Markdown Extensions
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

# Extra JavaScript, needed for LaTeX formatting
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css