site_name: CS3244 PG26 Documentation
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
